spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_show?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: Zhang!qaz@wsx123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
  redisson:
    address: localhost:6379
#    address: redis4gpmall.redis.rds.aliyuncs.com:6379
#    password: redis4GPMALL
    timeout: 3000
    database: 0
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 3000
      min-idle: 4
  ##以下下配置是springboot autoconfig 认初始化时会加载的参数，但是user可以重现构建一下参数
  ##自定义构造的bean可查看kafkaConfig
dubbo:
  application:
    name: comment-service
    owner: zcl
  protocol:
    name: dubbo
    port: 20884
  registry:
    address: zookeeper://localhost:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://localhost:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.mall.show.comment.service
